# Frontend service Dockerfile
FROM node:18-alpine AS build

WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm install

COPY public ./public
COPY src ./src
COPY config-overrides.js ./
COPY tailwind.config.js postcss.config.js ./
COPY README.md ./

ENV NODE_ENV=production
RUN npm run build

FROM nginx:1.27-alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
