FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY backend ./backend
COPY artifacts ./artifacts
COPY deployments ./deployments

ENV PORT=4000
EXPOSE 4000

CMD ["node", "backend/server.js"]
